# Welcome to Jekyll!

title: Anshu's Databook
author:
  name: Himanshu Panwar
  email: 047himanshu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Free Python and Machine Learning Tutorials. Data Science, Machine Learning, Computer Vision, 
  and Teaching are my passion. This blog is an extension of my passion in helping students and 
  data enthusiast learn about Data Science.
baseurl: "/my_blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

minima:
  # generate social links in footer
  social_links:
    twitter: hemanshup_
    github:  myselfhimanshu
    
# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

include: [_pages]

sass:
  style: compressed

defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post
      permalink: /blog/:title/
  -
    scope:
      type: pages
      path: _pages
    values:
      is_post: false
      layout: default

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
